### ISSUE TITLE
[Question] How could I use this with gles commands?

### ISSUE THREAD

**Issue by IanPhilips** [keijiro/TextureUpdateExample#6]
Hi, many thanks for the repo!

I'm trying to update a unity texture from a framebuffer :

    if (event == kUnityRenderingExtEventUpdateTextureBeginV2)
    {
        glBindFramebuffer(GL_FRAMEBUFFER, static_cast<GLuint>(g_FBOPointer));
        checkGlError("glBindTexture2d");

        glBindTexture(GL_TEXTURE_2D, static_cast<GLuint>(g_TexturePointer));
        checkGlError("glbindTexture2D");
        glCopyTexSubImage2D(GL_TEXTURE_2D,0,0,0,0,0,params->width,params->height);
        checkGlError("glCopyTexImage2D");
    }

but the texture remains black, (though I can see the framebuffer has images in it with an android imageview and glReadPixels).

Happen to have any tips? It's for [this](https://github.com/IanPhilips/UnityAndroidVRARBrowser) open source repo, Thanks!

**Comment by IanPhilips** [comment]
I noticed that the int returned via `params->textureID` is different than the texture id I create in my Start() function and later pass to the plugin, that seems like a problem. Is the textureID from params supposed to work?

**Comment by keijiro** [comment]
Could you submit a bug report with the built-in bug reporter about [this issue](https://github.com/keijiro/TextureUpdateExample/issues/6#issuecomment-460834686)? It seems like a reproducible bug.

That aside, I think it's better to use `IssuePluginEventAndData` for that case, because the main usage of CustomTextureUpdate is updating a texture via `params->texData`.

**Comment by IanPhilips** [comment]
Will do, thanks for the tip!
